apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pavloandriiesh-com-tls
spec:
  secretName: pavloandriiesh-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pavloandriiesh.com
  dnsNames:
    - pavloandriiesh.com
    - www.pavloandriiesh.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - pavloandriiesh.com
          - www.pavloandriiesh.com